/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResource } from './UserResource';
import {
    UserResourceFromJSON,
    UserResourceFromJSONTyped,
    UserResourceToJSON,
    UserResourceToJSONTyped,
} from './UserResource';

/**
 * 
 * @export
 * @interface AuthTokenResponse
 */
export interface AuthTokenResponse {
    /**
     * 
     * @type {UserResource}
     * @memberof AuthTokenResponse
     */
    user: UserResource;
    /**
     * 
     * @type {string}
     * @memberof AuthTokenResponse
     */
    token: string;
}

/**
 * Check if a given object implements the AuthTokenResponse interface.
 */
export function instanceOfAuthTokenResponse(value: object): value is AuthTokenResponse {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function AuthTokenResponseFromJSON(json: any): AuthTokenResponse {
    return AuthTokenResponseFromJSONTyped(json, false);
}

export function AuthTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserResourceFromJSON(json['user']),
        'token': json['token'],
    };
}

export function AuthTokenResponseToJSON(json: any): AuthTokenResponse {
    return AuthTokenResponseToJSONTyped(json, false);
}

export function AuthTokenResponseToJSONTyped(value?: AuthTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserResourceToJSON(value['user']),
        'token': value['token'],
    };
}

