/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BackgroundResource } from './BackgroundResource';
import {
    BackgroundResourceFromJSON,
    BackgroundResourceFromJSONTyped,
    BackgroundResourceToJSON,
    BackgroundResourceToJSONTyped,
} from './BackgroundResource';

/**
 * 
 * @export
 * @interface BackgroundCollection
 */
export interface BackgroundCollection {
    /**
     * 
     * @type {Array<BackgroundResource>}
     * @memberof BackgroundCollection
     */
    data?: Array<BackgroundResource>;
    /**
     * 
     * @type {object}
     * @memberof BackgroundCollection
     */
    links?: object;
    /**
     * 
     * @type {object}
     * @memberof BackgroundCollection
     */
    meta?: object;
}

/**
 * Check if a given object implements the BackgroundCollection interface.
 */
export function instanceOfBackgroundCollection(value: object): value is BackgroundCollection {
    return true;
}

export function BackgroundCollectionFromJSON(json: any): BackgroundCollection {
    return BackgroundCollectionFromJSONTyped(json, false);
}

export function BackgroundCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackgroundCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(BackgroundResourceFromJSON)),
        'links': json['links'] == null ? undefined : json['links'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function BackgroundCollectionToJSON(json: any): BackgroundCollection {
    return BackgroundCollectionToJSONTyped(json, false);
}

export function BackgroundCollectionToJSONTyped(value?: BackgroundCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(BackgroundResourceToJSON)),
        'links': value['links'],
        'meta': value['meta'],
    };
}

