/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BackgroundResource } from './BackgroundResource';
import {
    BackgroundResourceFromJSON,
    BackgroundResourceFromJSONTyped,
    BackgroundResourceToJSON,
    BackgroundResourceToJSONTyped,
} from './BackgroundResource';

/**
 * 
 * @export
 * @interface BackgroundResourceEnvelope
 */
export interface BackgroundResourceEnvelope {
    /**
     * 
     * @type {BackgroundResource}
     * @memberof BackgroundResourceEnvelope
     */
    data?: BackgroundResource;
}

/**
 * Check if a given object implements the BackgroundResourceEnvelope interface.
 */
export function instanceOfBackgroundResourceEnvelope(value: object): value is BackgroundResourceEnvelope {
    return true;
}

export function BackgroundResourceEnvelopeFromJSON(json: any): BackgroundResourceEnvelope {
    return BackgroundResourceEnvelopeFromJSONTyped(json, false);
}

export function BackgroundResourceEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackgroundResourceEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : BackgroundResourceFromJSON(json['data']),
    };
}

export function BackgroundResourceEnvelopeToJSON(json: any): BackgroundResourceEnvelope {
    return BackgroundResourceEnvelopeToJSONTyped(json, false);
}

export function BackgroundResourceEnvelopeToJSONTyped(value?: BackgroundResourceEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': BackgroundResourceToJSON(value['data']),
    };
}

