/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BackgroundResource
 */
export interface BackgroundResource {
    /**
     * 
     * @type {string}
     * @memberof BackgroundResource
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BackgroundResource
     */
    kind: BackgroundResourceKindEnum;
    /**
     * 
     * @type {string}
     * @memberof BackgroundResource
     */
    storageKey: string;
    /**
     * 
     * @type {string}
     * @memberof BackgroundResource
     */
    signedUrl: string;
    /**
     * 
     * @type {number}
     * @memberof BackgroundResource
     */
    width: number;
    /**
     * 
     * @type {number}
     * @memberof BackgroundResource
     */
    height: number;
    /**
     * 
     * @type {string}
     * @memberof BackgroundResource
     */
    prompt?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof BackgroundResource
     */
    isActive: boolean;
    /**
     * 
     * @type {Date}
     * @memberof BackgroundResource
     */
    createdAt: Date;
}


/**
 * @export
 */
export const BackgroundResourceKindEnum = {
    Upload: 'upload',
    Generated: 'generated',
    Preset: 'preset'
} as const;
export type BackgroundResourceKindEnum = typeof BackgroundResourceKindEnum[keyof typeof BackgroundResourceKindEnum];


/**
 * Check if a given object implements the BackgroundResource interface.
 */
export function instanceOfBackgroundResource(value: object): value is BackgroundResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('storageKey' in value) || value['storageKey'] === undefined) return false;
    if (!('signedUrl' in value) || value['signedUrl'] === undefined) return false;
    if (!('width' in value) || value['width'] === undefined) return false;
    if (!('height' in value) || value['height'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function BackgroundResourceFromJSON(json: any): BackgroundResource {
    return BackgroundResourceFromJSONTyped(json, false);
}

export function BackgroundResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackgroundResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'kind': json['kind'],
        'storageKey': json['storage_key'],
        'signedUrl': json['signed_url'],
        'width': json['width'],
        'height': json['height'],
        'prompt': json['prompt'] == null ? undefined : json['prompt'],
        'isActive': json['is_active'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function BackgroundResourceToJSON(json: any): BackgroundResource {
    return BackgroundResourceToJSONTyped(json, false);
}

export function BackgroundResourceToJSONTyped(value?: BackgroundResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'kind': value['kind'],
        'storage_key': value['storageKey'],
        'signed_url': value['signedUrl'],
        'width': value['width'],
        'height': value['height'],
        'prompt': value['prompt'],
        'is_active': value['isActive'],
        'created_at': ((value['createdAt']).toISOString()),
    };
}

