/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClaimUsernameRequest
 */
export interface ClaimUsernameRequest {
    /**
     * 
     * @type {string}
     * @memberof ClaimUsernameRequest
     */
    username: string;
}

/**
 * Check if a given object implements the ClaimUsernameRequest interface.
 */
export function instanceOfClaimUsernameRequest(value: object): value is ClaimUsernameRequest {
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function ClaimUsernameRequestFromJSON(json: any): ClaimUsernameRequest {
    return ClaimUsernameRequestFromJSONTyped(json, false);
}

export function ClaimUsernameRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimUsernameRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
    };
}

export function ClaimUsernameRequestToJSON(json: any): ClaimUsernameRequest {
    return ClaimUsernameRequestToJSONTyped(json, false);
}

export function ClaimUsernameRequestToJSONTyped(value?: ClaimUsernameRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
    };
}

