/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FishBreedResource } from './FishBreedResource';
import {
    FishBreedResourceFromJSON,
    FishBreedResourceFromJSONTyped,
    FishBreedResourceToJSON,
    FishBreedResourceToJSONTyped,
} from './FishBreedResource';

/**
 * 
 * @export
 * @interface FishBreedCollection
 */
export interface FishBreedCollection {
    /**
     * 
     * @type {Array<FishBreedResource>}
     * @memberof FishBreedCollection
     */
    data?: Array<FishBreedResource>;
}

/**
 * Check if a given object implements the FishBreedCollection interface.
 */
export function instanceOfFishBreedCollection(value: object): value is FishBreedCollection {
    return true;
}

export function FishBreedCollectionFromJSON(json: any): FishBreedCollection {
    return FishBreedCollectionFromJSONTyped(json, false);
}

export function FishBreedCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FishBreedCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(FishBreedResourceFromJSON)),
    };
}

export function FishBreedCollectionToJSON(json: any): FishBreedCollection {
    return FishBreedCollectionToJSONTyped(json, false);
}

export function FishBreedCollectionToJSONTyped(value?: FishBreedCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(FishBreedResourceToJSON)),
    };
}

