/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FishResource
 */
export interface FishResource {
    /**
     * 
     * @type {string}
     * @memberof FishResource
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FishResource
     */
    nickname: string;
    /**
     * 
     * @type {string}
     * @memberof FishResource
     */
    breed: string;
    /**
     * 
     * @type {string}
     * @memberof FishResource
     */
    colorHex: string;
    /**
     * 
     * @type {number}
     * @memberof FishResource
     */
    size: number;
    /**
     * 
     * @type {string}
     * @memberof FishResource
     */
    source: FishResourceSourceEnum;
    /**
     * 
     * @type {string}
     * @memberof FishResource
     */
    sourceRef?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof FishResource
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof FishResource
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const FishResourceSourceEnum = {
    Manual: 'manual',
    GithubRepo: 'github_repo'
} as const;
export type FishResourceSourceEnum = typeof FishResourceSourceEnum[keyof typeof FishResourceSourceEnum];


/**
 * Check if a given object implements the FishResource interface.
 */
export function instanceOfFishResource(value: object): value is FishResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    if (!('breed' in value) || value['breed'] === undefined) return false;
    if (!('colorHex' in value) || value['colorHex'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function FishResourceFromJSON(json: any): FishResource {
    return FishResourceFromJSONTyped(json, false);
}

export function FishResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): FishResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'nickname': json['nickname'],
        'breed': json['breed'],
        'colorHex': json['color_hex'],
        'size': json['size'],
        'source': json['source'],
        'sourceRef': json['source_ref'] == null ? undefined : json['source_ref'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function FishResourceToJSON(json: any): FishResource {
    return FishResourceToJSONTyped(json, false);
}

export function FishResourceToJSONTyped(value?: FishResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'nickname': value['nickname'],
        'breed': value['breed'],
        'color_hex': value['colorHex'],
        'size': value['size'],
        'source': value['source'],
        'source_ref': value['sourceRef'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

