/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FishResource } from './FishResource';
import {
    FishResourceFromJSON,
    FishResourceFromJSONTyped,
    FishResourceToJSON,
    FishResourceToJSONTyped,
} from './FishResource';

/**
 * 
 * @export
 * @interface FishResourceEnvelope
 */
export interface FishResourceEnvelope {
    /**
     * 
     * @type {FishResource}
     * @memberof FishResourceEnvelope
     */
    data?: FishResource;
}

/**
 * Check if a given object implements the FishResourceEnvelope interface.
 */
export function instanceOfFishResourceEnvelope(value: object): value is FishResourceEnvelope {
    return true;
}

export function FishResourceEnvelopeFromJSON(json: any): FishResourceEnvelope {
    return FishResourceEnvelopeFromJSONTyped(json, false);
}

export function FishResourceEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FishResourceEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : FishResourceFromJSON(json['data']),
    };
}

export function FishResourceEnvelopeToJSON(json: any): FishResourceEnvelope {
    return FishResourceEnvelopeToJSONTyped(json, false);
}

export function FishResourceEnvelopeToJSONTyped(value?: FishResourceEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': FishResourceToJSON(value['data']),
    };
}

