/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FishBreedResource
 */
export interface FishBreedResource {
    /**
     * 
     * @type {string}
     * @memberof FishBreedResource
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof FishBreedResource
     */
    label: string;
    /**
     * 
     * @type {number}
     * @memberof FishBreedResource
     */
    minSize: number;
    /**
     * 
     * @type {number}
     * @memberof FishBreedResource
     */
    maxSize: number;
    /**
     * 
     * @type {string}
     * @memberof FishBreedResource
     */
    defaultColor: string;
    /**
     * 
     * @type {string}
     * @memberof FishBreedResource
     */
    spriteKey: string;
    /**
     * 
     * @type {string}
     * @memberof FishBreedResource
     */
    verticalBandPreference?: FishBreedResourceVerticalBandPreferenceEnum | null;
}


/**
 * @export
 */
export const FishBreedResourceVerticalBandPreferenceEnum = {
    Bottom: 'bottom'
} as const;
export type FishBreedResourceVerticalBandPreferenceEnum = typeof FishBreedResourceVerticalBandPreferenceEnum[keyof typeof FishBreedResourceVerticalBandPreferenceEnum];


/**
 * Check if a given object implements the FishBreedResource interface.
 */
export function instanceOfFishBreedResource(value: object): value is FishBreedResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('minSize' in value) || value['minSize'] === undefined) return false;
    if (!('maxSize' in value) || value['maxSize'] === undefined) return false;
    if (!('defaultColor' in value) || value['defaultColor'] === undefined) return false;
    if (!('spriteKey' in value) || value['spriteKey'] === undefined) return false;
    return true;
}

export function FishBreedResourceFromJSON(json: any): FishBreedResource {
    return FishBreedResourceFromJSONTyped(json, false);
}

export function FishBreedResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): FishBreedResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'label': json['label'],
        'minSize': json['min_size'],
        'maxSize': json['max_size'],
        'defaultColor': json['default_color'],
        'spriteKey': json['sprite_key'],
        'verticalBandPreference': json['vertical_band_preference'] == null ? undefined : json['vertical_band_preference'],
    };
}

export function FishBreedResourceToJSON(json: any): FishBreedResource {
    return FishBreedResourceToJSONTyped(json, false);
}

export function FishBreedResourceToJSONTyped(value?: FishBreedResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'label': value['label'],
        'min_size': value['minSize'],
        'max_size': value['maxSize'],
        'default_color': value['defaultColor'],
        'sprite_key': value['spriteKey'],
        'vertical_band_preference': value['verticalBandPreference'],
    };
}

