/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateBackgroundRequest
 */
export interface GenerateBackgroundRequest {
    /**
     * 
     * @type {string}
     * @memberof GenerateBackgroundRequest
     */
    prompt: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateBackgroundRequest
     */
    aspectRatio?: GenerateBackgroundRequestAspectRatioEnum;
}


/**
 * @export
 */
export const GenerateBackgroundRequestAspectRatioEnum = {
    _169: '16:9',
    _32: '3:2',
    _11: '1:1'
} as const;
export type GenerateBackgroundRequestAspectRatioEnum = typeof GenerateBackgroundRequestAspectRatioEnum[keyof typeof GenerateBackgroundRequestAspectRatioEnum];


/**
 * Check if a given object implements the GenerateBackgroundRequest interface.
 */
export function instanceOfGenerateBackgroundRequest(value: object): value is GenerateBackgroundRequest {
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function GenerateBackgroundRequestFromJSON(json: any): GenerateBackgroundRequest {
    return GenerateBackgroundRequestFromJSONTyped(json, false);
}

export function GenerateBackgroundRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateBackgroundRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'],
        'aspectRatio': json['aspect_ratio'] == null ? undefined : json['aspect_ratio'],
    };
}

export function GenerateBackgroundRequestToJSON(json: any): GenerateBackgroundRequest {
    return GenerateBackgroundRequestToJSONTyped(json, false);
}

export function GenerateBackgroundRequestToJSONTyped(value?: GenerateBackgroundRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
        'aspect_ratio': value['aspectRatio'],
    };
}

