/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResource } from './UserResource';
import {
    UserResourceFromJSON,
    UserResourceFromJSONTyped,
    UserResourceToJSON,
    UserResourceToJSONTyped,
} from './UserResource';

/**
 * 
 * @export
 * @interface MeResponse
 */
export interface MeResponse {
    /**
     * 
     * @type {UserResource}
     * @memberof MeResponse
     */
    user: UserResource;
}

/**
 * Check if a given object implements the MeResponse interface.
 */
export function instanceOfMeResponse(value: object): value is MeResponse {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function MeResponseFromJSON(json: any): MeResponse {
    return MeResponseFromJSONTyped(json, false);
}

export function MeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'user': UserResourceFromJSON(json['user']),
    };
}

export function MeResponseToJSON(json: any): MeResponse {
    return MeResponseToJSONTyped(json, false);
}

export function MeResponseToJSONTyped(value?: MeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserResourceToJSON(value['user']),
    };
}

