/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model948a42bdb65c02ff487237856eef1afe200Response
 */
export interface Model948a42bdb65c02ff487237856eef1afe200Response {
    /**
     * 
     * @type {boolean}
     * @memberof Model948a42bdb65c02ff487237856eef1afe200Response
     */
    ok?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Model948a42bdb65c02ff487237856eef1afe200Response
     */
    version?: string;
}

/**
 * Check if a given object implements the Model948a42bdb65c02ff487237856eef1afe200Response interface.
 */
export function instanceOfModel948a42bdb65c02ff487237856eef1afe200Response(value: object): value is Model948a42bdb65c02ff487237856eef1afe200Response {
    return true;
}

export function Model948a42bdb65c02ff487237856eef1afe200ResponseFromJSON(json: any): Model948a42bdb65c02ff487237856eef1afe200Response {
    return Model948a42bdb65c02ff487237856eef1afe200ResponseFromJSONTyped(json, false);
}

export function Model948a42bdb65c02ff487237856eef1afe200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model948a42bdb65c02ff487237856eef1afe200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'] == null ? undefined : json['ok'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function Model948a42bdb65c02ff487237856eef1afe200ResponseToJSON(json: any): Model948a42bdb65c02ff487237856eef1afe200Response {
    return Model948a42bdb65c02ff487237856eef1afe200ResponseToJSONTyped(json, false);
}

export function Model948a42bdb65c02ff487237856eef1afe200ResponseToJSONTyped(value?: Model948a42bdb65c02ff487237856eef1afe200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'version': value['version'],
    };
}

