/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FishResource } from './FishResource';
import {
    FishResourceFromJSON,
    FishResourceFromJSONTyped,
    FishResourceToJSON,
    FishResourceToJSONTyped,
} from './FishResource';

/**
 * 
 * @export
 * @interface PaginatedFishCollection
 */
export interface PaginatedFishCollection {
    /**
     * 
     * @type {Array<FishResource>}
     * @memberof PaginatedFishCollection
     */
    data?: Array<FishResource>;
    /**
     * 
     * @type {object}
     * @memberof PaginatedFishCollection
     */
    links?: object;
    /**
     * 
     * @type {object}
     * @memberof PaginatedFishCollection
     */
    meta?: object;
}

/**
 * Check if a given object implements the PaginatedFishCollection interface.
 */
export function instanceOfPaginatedFishCollection(value: object): value is PaginatedFishCollection {
    return true;
}

export function PaginatedFishCollectionFromJSON(json: any): PaginatedFishCollection {
    return PaginatedFishCollectionFromJSONTyped(json, false);
}

export function PaginatedFishCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedFishCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(FishResourceFromJSON)),
        'links': json['links'] == null ? undefined : json['links'],
        'meta': json['meta'] == null ? undefined : json['meta'],
    };
}

export function PaginatedFishCollectionToJSON(json: any): PaginatedFishCollection {
    return PaginatedFishCollectionToJSONTyped(json, false);
}

export function PaginatedFishCollectionToJSONTyped(value?: PaginatedFishCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(FishResourceToJSON)),
        'links': value['links'],
        'meta': value['meta'],
    };
}

