/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RepoStats } from './RepoStats';
import {
    RepoStatsFromJSON,
    RepoStatsFromJSONTyped,
    RepoStatsToJSON,
    RepoStatsToJSONTyped,
} from './RepoStats';
import type { RepoFishItem } from './RepoFishItem';
import {
    RepoFishItemFromJSON,
    RepoFishItemFromJSONTyped,
    RepoFishItemToJSON,
    RepoFishItemToJSONTyped,
} from './RepoFishItem';

/**
 * 
 * @export
 * @interface RepoAquariumResponseData
 */
export interface RepoAquariumResponseData {
    /**
     * 
     * @type {RepoStats}
     * @memberof RepoAquariumResponseData
     */
    stats?: RepoStats;
    /**
     * 
     * @type {Array<RepoFishItem>}
     * @memberof RepoAquariumResponseData
     */
    fishSet?: Array<RepoFishItem>;
}

/**
 * Check if a given object implements the RepoAquariumResponseData interface.
 */
export function instanceOfRepoAquariumResponseData(value: object): value is RepoAquariumResponseData {
    return true;
}

export function RepoAquariumResponseDataFromJSON(json: any): RepoAquariumResponseData {
    return RepoAquariumResponseDataFromJSONTyped(json, false);
}

export function RepoAquariumResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepoAquariumResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'stats': json['stats'] == null ? undefined : RepoStatsFromJSON(json['stats']),
        'fishSet': json['fish_set'] == null ? undefined : ((json['fish_set'] as Array<any>).map(RepoFishItemFromJSON)),
    };
}

export function RepoAquariumResponseDataToJSON(json: any): RepoAquariumResponseData {
    return RepoAquariumResponseDataToJSONTyped(json, false);
}

export function RepoAquariumResponseDataToJSONTyped(value?: RepoAquariumResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stats': RepoStatsToJSON(value['stats']),
        'fish_set': value['fishSet'] == null ? undefined : ((value['fishSet'] as Array<any>).map(RepoFishItemToJSON)),
    };
}

