/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RepoAquariumErrorResponse
 */
export interface RepoAquariumErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof RepoAquariumErrorResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the RepoAquariumErrorResponse interface.
 */
export function instanceOfRepoAquariumErrorResponse(value: object): value is RepoAquariumErrorResponse {
    return true;
}

export function RepoAquariumErrorResponseFromJSON(json: any): RepoAquariumErrorResponse {
    return RepoAquariumErrorResponseFromJSONTyped(json, false);
}

export function RepoAquariumErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepoAquariumErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function RepoAquariumErrorResponseToJSON(json: any): RepoAquariumErrorResponse {
    return RepoAquariumErrorResponseToJSONTyped(json, false);
}

export function RepoAquariumErrorResponseToJSONTyped(value?: RepoAquariumErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

