/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RepoFishItem
 */
export interface RepoFishItem {
    /**
     * 
     * @type {string}
     * @memberof RepoFishItem
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RepoFishItem
     */
    breed?: string;
    /**
     * 
     * @type {string}
     * @memberof RepoFishItem
     */
    colorHex?: string;
    /**
     * 
     * @type {number}
     * @memberof RepoFishItem
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof RepoFishItem
     */
    nickname?: string;
    /**
     * 
     * @type {string}
     * @memberof RepoFishItem
     */
    source?: string;
    /**
     * 
     * @type {string}
     * @memberof RepoFishItem
     */
    sourceRef?: string;
}

/**
 * Check if a given object implements the RepoFishItem interface.
 */
export function instanceOfRepoFishItem(value: object): value is RepoFishItem {
    return true;
}

export function RepoFishItemFromJSON(json: any): RepoFishItem {
    return RepoFishItemFromJSONTyped(json, false);
}

export function RepoFishItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepoFishItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'breed': json['breed'] == null ? undefined : json['breed'],
        'colorHex': json['color_hex'] == null ? undefined : json['color_hex'],
        'size': json['size'] == null ? undefined : json['size'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'source': json['source'] == null ? undefined : json['source'],
        'sourceRef': json['source_ref'] == null ? undefined : json['source_ref'],
    };
}

export function RepoFishItemToJSON(json: any): RepoFishItem {
    return RepoFishItemToJSONTyped(json, false);
}

export function RepoFishItemToJSONTyped(value?: RepoFishItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'breed': value['breed'],
        'color_hex': value['colorHex'],
        'size': value['size'],
        'nickname': value['nickname'],
        'source': value['source'],
        'source_ref': value['sourceRef'],
    };
}

