/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RepoForkResponse
 */
export interface RepoForkResponse {
    /**
     * 
     * @type {number}
     * @memberof RepoForkResponse
     */
    added?: number;
}

/**
 * Check if a given object implements the RepoForkResponse interface.
 */
export function instanceOfRepoForkResponse(value: object): value is RepoForkResponse {
    return true;
}

export function RepoForkResponseFromJSON(json: any): RepoForkResponse {
    return RepoForkResponseFromJSONTyped(json, false);
}

export function RepoForkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepoForkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'added': json['added'] == null ? undefined : json['added'],
    };
}

export function RepoForkResponseToJSON(json: any): RepoForkResponse {
    return RepoForkResponseToJSONTyped(json, false);
}

export function RepoForkResponseToJSONTyped(value?: RepoForkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'added': value['added'],
    };
}

