/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RepoAquariumResponseData } from './RepoAquariumResponseData';
import {
    RepoAquariumResponseDataFromJSON,
    RepoAquariumResponseDataFromJSONTyped,
    RepoAquariumResponseDataToJSON,
    RepoAquariumResponseDataToJSONTyped,
} from './RepoAquariumResponseData';

/**
 * 
 * @export
 * @interface RepoAquariumResponse
 */
export interface RepoAquariumResponse {
    /**
     * 
     * @type {RepoAquariumResponseData}
     * @memberof RepoAquariumResponse
     */
    data?: RepoAquariumResponseData;
}

/**
 * Check if a given object implements the RepoAquariumResponse interface.
 */
export function instanceOfRepoAquariumResponse(value: object): value is RepoAquariumResponse {
    return true;
}

export function RepoAquariumResponseFromJSON(json: any): RepoAquariumResponse {
    return RepoAquariumResponseFromJSONTyped(json, false);
}

export function RepoAquariumResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepoAquariumResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : RepoAquariumResponseDataFromJSON(json['data']),
    };
}

export function RepoAquariumResponseToJSON(json: any): RepoAquariumResponse {
    return RepoAquariumResponseToJSONTyped(json, false);
}

export function RepoAquariumResponseToJSONTyped(value?: RepoAquariumResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': RepoAquariumResponseDataToJSON(value['data']),
    };
}

