/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RepoStats
 */
export interface RepoStats {
    /**
     * 
     * @type {number}
     * @memberof RepoStats
     */
    stars?: number;
    /**
     * 
     * @type {number}
     * @memberof RepoStats
     */
    forks?: number;
    /**
     * 
     * @type {number}
     * @memberof RepoStats
     */
    issues?: number;
    /**
     * 
     * @type {number}
     * @memberof RepoStats
     */
    watchers?: number;
    /**
     * 
     * @type {number}
     * @memberof RepoStats
     */
    contributors?: number;
    /**
     * 
     * @type {string}
     * @memberof RepoStats
     */
    language?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RepoStats
     */
    ageDays?: number;
    /**
     * 
     * @type {Date}
     * @memberof RepoStats
     */
    fetchedAt?: Date;
}

/**
 * Check if a given object implements the RepoStats interface.
 */
export function instanceOfRepoStats(value: object): value is RepoStats {
    return true;
}

export function RepoStatsFromJSON(json: any): RepoStats {
    return RepoStatsFromJSONTyped(json, false);
}

export function RepoStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepoStats {
    if (json == null) {
        return json;
    }
    return {
        
        'stars': json['stars'] == null ? undefined : json['stars'],
        'forks': json['forks'] == null ? undefined : json['forks'],
        'issues': json['issues'] == null ? undefined : json['issues'],
        'watchers': json['watchers'] == null ? undefined : json['watchers'],
        'contributors': json['contributors'] == null ? undefined : json['contributors'],
        'language': json['language'] == null ? undefined : json['language'],
        'ageDays': json['age_days'] == null ? undefined : json['age_days'],
        'fetchedAt': json['fetched_at'] == null ? undefined : (new Date(json['fetched_at'])),
    };
}

export function RepoStatsToJSON(json: any): RepoStats {
    return RepoStatsToJSONTyped(json, false);
}

export function RepoStatsToJSONTyped(value?: RepoStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stars': value['stars'],
        'forks': value['forks'],
        'issues': value['issues'],
        'watchers': value['watchers'],
        'contributors': value['contributors'],
        'language': value['language'],
        'age_days': value['ageDays'],
        'fetched_at': value['fetchedAt'] == null ? undefined : ((value['fetchedAt']).toISOString()),
    };
}

