/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoreFishRequest
 */
export interface StoreFishRequest {
    /**
     * 
     * @type {string}
     * @memberof StoreFishRequest
     */
    nickname: string;
    /**
     * 
     * @type {string}
     * @memberof StoreFishRequest
     */
    breed: string;
    /**
     * 
     * @type {string}
     * @memberof StoreFishRequest
     */
    colorHex: string;
    /**
     * 
     * @type {number}
     * @memberof StoreFishRequest
     */
    size: number;
}

/**
 * Check if a given object implements the StoreFishRequest interface.
 */
export function instanceOfStoreFishRequest(value: object): value is StoreFishRequest {
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    if (!('breed' in value) || value['breed'] === undefined) return false;
    if (!('colorHex' in value) || value['colorHex'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    return true;
}

export function StoreFishRequestFromJSON(json: any): StoreFishRequest {
    return StoreFishRequestFromJSONTyped(json, false);
}

export function StoreFishRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreFishRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'nickname': json['nickname'],
        'breed': json['breed'],
        'colorHex': json['color_hex'],
        'size': json['size'],
    };
}

export function StoreFishRequestToJSON(json: any): StoreFishRequest {
    return StoreFishRequestToJSONTyped(json, false);
}

export function StoreFishRequestToJSONTyped(value?: StoreFishRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nickname': value['nickname'],
        'breed': value['breed'],
        'color_hex': value['colorHex'],
        'size': value['size'],
    };
}

