/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateFishRequest
 */
export interface UpdateFishRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateFishRequest
     */
    nickname?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFishRequest
     */
    colorHex?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateFishRequest
     */
    size?: number;
}

/**
 * Check if a given object implements the UpdateFishRequest interface.
 */
export function instanceOfUpdateFishRequest(value: object): value is UpdateFishRequest {
    return true;
}

export function UpdateFishRequestFromJSON(json: any): UpdateFishRequest {
    return UpdateFishRequestFromJSONTyped(json, false);
}

export function UpdateFishRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateFishRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'colorHex': json['color_hex'] == null ? undefined : json['color_hex'],
        'size': json['size'] == null ? undefined : json['size'],
    };
}

export function UpdateFishRequestToJSON(json: any): UpdateFishRequest {
    return UpdateFishRequestToJSONTyped(json, false);
}

export function UpdateFishRequestToJSONTyped(value?: UpdateFishRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nickname': value['nickname'],
        'color_hex': value['colorHex'],
        'size': value['size'],
    };
}

