/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserResource
 */
export interface UserResource {
    /**
     * 
     * @type {number}
     * @memberof UserResource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserResource
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserResource
     */
    email: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserResource
     */
    isAdmin: boolean;
    /**
     * 
     * @type {Date}
     * @memberof UserResource
     */
    emailVerifiedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof UserResource
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the UserResource interface.
 */
export function instanceOfUserResource(value: object): value is UserResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('isAdmin' in value) || value['isAdmin'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function UserResourceFromJSON(json: any): UserResource {
    return UserResourceFromJSONTyped(json, false);
}

export function UserResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'email': json['email'],
        'isAdmin': json['is_admin'],
        'emailVerifiedAt': json['email_verified_at'] == null ? undefined : (new Date(json['email_verified_at'])),
        'createdAt': (new Date(json['created_at'])),
    };
}

export function UserResourceToJSON(json: any): UserResource {
    return UserResourceToJSONTyped(json, false);
}

export function UserResourceToJSONTyped(value?: UserResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'email': value['email'],
        'is_admin': value['isAdmin'],
        'email_verified_at': value['emailVerifiedAt'] == null ? undefined : ((value['emailVerifiedAt'] as any).toISOString()),
        'created_at': ((value['createdAt']).toISOString()),
    };
}

