/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BackgroundCollection,
  BackgroundResourceEnvelope,
  GenerateBackgroundRequest,
} from '../models/index';
import {
    BackgroundCollectionFromJSON,
    BackgroundCollectionToJSON,
    BackgroundResourceEnvelopeFromJSON,
    BackgroundResourceEnvelopeToJSON,
    GenerateBackgroundRequestFromJSON,
    GenerateBackgroundRequestToJSON,
} from '../models/index';

export interface DeleteBackgroundRequest {
    background: string;
}

export interface GenerateBackgroundOperationRequest {
    generateBackgroundRequest: GenerateBackgroundRequest;
}

export interface ListBackgroundsRequest {
    page?: number;
    perPage?: number;
}

export interface SelectBackgroundRequest {
    background: string;
}

export interface UploadBackgroundRequest {
    image: Blob;
}

/**
 * 
 */
export class BackgroundsApi extends runtime.BaseAPI {

    /**
     */
    async deleteBackgroundRaw(requestParameters: DeleteBackgroundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['background'] == null) {
            throw new runtime.RequiredError(
                'background',
                'Required parameter "background" was null or undefined when calling deleteBackground().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/backgrounds/{background}`.replace(`{${"background"}}`, encodeURIComponent(String(requestParameters['background']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteBackground(requestParameters: DeleteBackgroundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteBackgroundRaw(requestParameters, initOverrides);
    }

    /**
     */
    async generateBackgroundRaw(requestParameters: GenerateBackgroundOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackgroundResourceEnvelope>> {
        if (requestParameters['generateBackgroundRequest'] == null) {
            throw new runtime.RequiredError(
                'generateBackgroundRequest',
                'Required parameter "generateBackgroundRequest" was null or undefined when calling generateBackground().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/backgrounds/generate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GenerateBackgroundRequestToJSON(requestParameters['generateBackgroundRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackgroundResourceEnvelopeFromJSON(jsonValue));
    }

    /**
     */
    async generateBackground(requestParameters: GenerateBackgroundOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackgroundResourceEnvelope> {
        const response = await this.generateBackgroundRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listBackgroundsRaw(requestParameters: ListBackgroundsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackgroundCollection>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/backgrounds`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackgroundCollectionFromJSON(jsonValue));
    }

    /**
     */
    async listBackgrounds(requestParameters: ListBackgroundsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackgroundCollection> {
        const response = await this.listBackgroundsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async selectBackgroundRaw(requestParameters: SelectBackgroundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackgroundResourceEnvelope>> {
        if (requestParameters['background'] == null) {
            throw new runtime.RequiredError(
                'background',
                'Required parameter "background" was null or undefined when calling selectBackground().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/backgrounds/{background}/select`.replace(`{${"background"}}`, encodeURIComponent(String(requestParameters['background']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackgroundResourceEnvelopeFromJSON(jsonValue));
    }

    /**
     */
    async selectBackground(requestParameters: SelectBackgroundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackgroundResourceEnvelope> {
        const response = await this.selectBackgroundRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async uploadBackgroundRaw(requestParameters: UploadBackgroundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackgroundResourceEnvelope>> {
        if (requestParameters['image'] == null) {
            throw new runtime.RequiredError(
                'image',
                'Required parameter "image" was null or undefined when calling uploadBackground().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['image'] != null) {
            formParams.append('image', requestParameters['image'] as any);
        }

        const response = await this.request({
            path: `/backgrounds/upload`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackgroundResourceEnvelopeFromJSON(jsonValue));
    }

    /**
     */
    async uploadBackground(requestParameters: UploadBackgroundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackgroundResourceEnvelope> {
        const response = await this.uploadBackgroundRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
