/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FishBreedCollection,
  FishResourceEnvelope,
  PaginatedFishCollection,
  StoreFishRequest,
  UpdateFishRequest,
} from '../models/index';
import {
    FishBreedCollectionFromJSON,
    FishBreedCollectionToJSON,
    FishResourceEnvelopeFromJSON,
    FishResourceEnvelopeToJSON,
    PaginatedFishCollectionFromJSON,
    PaginatedFishCollectionToJSON,
    StoreFishRequestFromJSON,
    StoreFishRequestToJSON,
    UpdateFishRequestFromJSON,
    UpdateFishRequestToJSON,
} from '../models/index';

export interface CreateFishRequest {
    storeFishRequest: StoreFishRequest;
}

export interface DeleteFishRequest {
    fish: number;
}

export interface GetFishRequest {
    fish: number;
}

export interface ListFishesRequest {
    search?: string;
    breed?: string;
    color?: string;
    sort?: ListFishesSortEnum;
    direction?: ListFishesDirectionEnum;
    page?: number;
    perPage?: number;
}

export interface UpdateFishOperationRequest {
    fish: number;
    updateFishRequest: UpdateFishRequest;
}

/**
 * 
 */
export class FishesApi extends runtime.BaseAPI {

    /**
     */
    async createFishRaw(requestParameters: CreateFishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FishResourceEnvelope>> {
        if (requestParameters['storeFishRequest'] == null) {
            throw new runtime.RequiredError(
                'storeFishRequest',
                'Required parameter "storeFishRequest" was null or undefined when calling createFish().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/fishes`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StoreFishRequestToJSON(requestParameters['storeFishRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FishResourceEnvelopeFromJSON(jsonValue));
    }

    /**
     */
    async createFish(requestParameters: CreateFishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FishResourceEnvelope> {
        const response = await this.createFishRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteFishRaw(requestParameters: DeleteFishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['fish'] == null) {
            throw new runtime.RequiredError(
                'fish',
                'Required parameter "fish" was null or undefined when calling deleteFish().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/fishes/{fish}`.replace(`{${"fish"}}`, encodeURIComponent(String(requestParameters['fish']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteFish(requestParameters: DeleteFishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteFishRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getFishRaw(requestParameters: GetFishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FishResourceEnvelope>> {
        if (requestParameters['fish'] == null) {
            throw new runtime.RequiredError(
                'fish',
                'Required parameter "fish" was null or undefined when calling getFish().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/fishes/{fish}`.replace(`{${"fish"}}`, encodeURIComponent(String(requestParameters['fish']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FishResourceEnvelopeFromJSON(jsonValue));
    }

    /**
     */
    async getFish(requestParameters: GetFishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FishResourceEnvelope> {
        const response = await this.getFishRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listBreedsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FishBreedCollection>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/fishes/breeds`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FishBreedCollectionFromJSON(jsonValue));
    }

    /**
     */
    async listBreeds(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FishBreedCollection> {
        const response = await this.listBreedsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async listFishesRaw(requestParameters: ListFishesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedFishCollection>> {
        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['breed'] != null) {
            queryParameters['breed'] = requestParameters['breed'];
        }

        if (requestParameters['color'] != null) {
            queryParameters['color'] = requestParameters['color'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/fishes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedFishCollectionFromJSON(jsonValue));
    }

    /**
     */
    async listFishes(requestParameters: ListFishesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedFishCollection> {
        const response = await this.listFishesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateFishRaw(requestParameters: UpdateFishOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FishResourceEnvelope>> {
        if (requestParameters['fish'] == null) {
            throw new runtime.RequiredError(
                'fish',
                'Required parameter "fish" was null or undefined when calling updateFish().'
            );
        }

        if (requestParameters['updateFishRequest'] == null) {
            throw new runtime.RequiredError(
                'updateFishRequest',
                'Required parameter "updateFishRequest" was null or undefined when calling updateFish().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/fishes/{fish}`.replace(`{${"fish"}}`, encodeURIComponent(String(requestParameters['fish']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateFishRequestToJSON(requestParameters['updateFishRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FishResourceEnvelopeFromJSON(jsonValue));
    }

    /**
     */
    async updateFish(requestParameters: UpdateFishOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FishResourceEnvelope> {
        const response = await this.updateFishRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListFishesSortEnum = {
    Name: 'name',
    Breed: 'breed',
    CreatedAt: 'created_at',
    Size: 'size'
} as const;
export type ListFishesSortEnum = typeof ListFishesSortEnum[keyof typeof ListFishesSortEnum];
/**
 * @export
 */
export const ListFishesDirectionEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type ListFishesDirectionEnum = typeof ListFishesDirectionEnum[keyof typeof ListFishesDirectionEnum];
