/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Model948a42bdb65c02ff487237856eef1afe200Response,
} from '../models/index';
import {
    Model948a42bdb65c02ff487237856eef1afe200ResponseFromJSON,
    Model948a42bdb65c02ff487237856eef1afe200ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class MetaApi extends runtime.BaseAPI {

    /**
     * Service liveness probe
     */
    async _948a42bdb65c02ff487237856eef1afeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Model948a42bdb65c02ff487237856eef1afe200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Model948a42bdb65c02ff487237856eef1afe200ResponseFromJSON(jsonValue));
    }

    /**
     * Service liveness probe
     */
    async _948a42bdb65c02ff487237856eef1afe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Model948a42bdb65c02ff487237856eef1afe200Response> {
        const response = await this._948a42bdb65c02ff487237856eef1afeRaw(initOverrides);
        return await response.value();
    }

}
