/* tslint:disable */
/* eslint-disable */
/**
 * Fishbook API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RepoAquariumErrorResponse,
  RepoAquariumResponse,
  RepoForkResponse,
} from '../models/index';
import {
    RepoAquariumErrorResponseFromJSON,
    RepoAquariumErrorResponseToJSON,
    RepoAquariumResponseFromJSON,
    RepoAquariumResponseToJSON,
    RepoForkResponseFromJSON,
    RepoForkResponseToJSON,
} from '../models/index';

export interface ForkRepoAquariumRequest {
    owner: string;
    repo: string;
}

export interface GetRepoAquariumRequest {
    owner: string;
    repo: string;
}

/**
 * 
 */
export class RepoAquariumApi extends runtime.BaseAPI {

    /**
     */
    async forkRepoAquariumRaw(requestParameters: ForkRepoAquariumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RepoForkResponse>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling forkRepoAquarium().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling forkRepoAquarium().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/repos/{owner}/{repo}/fork-to-my-aquarium`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RepoForkResponseFromJSON(jsonValue));
    }

    /**
     */
    async forkRepoAquarium(requestParameters: ForkRepoAquariumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RepoForkResponse> {
        const response = await this.forkRepoAquariumRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getRepoAquariumRaw(requestParameters: GetRepoAquariumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RepoAquariumResponse>> {
        if (requestParameters['owner'] == null) {
            throw new runtime.RequiredError(
                'owner',
                'Required parameter "owner" was null or undefined when calling getRepoAquarium().'
            );
        }

        if (requestParameters['repo'] == null) {
            throw new runtime.RequiredError(
                'repo',
                'Required parameter "repo" was null or undefined when calling getRepoAquarium().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/repos/{owner}/{repo}/aquarium`.replace(`{${"owner"}}`, encodeURIComponent(String(requestParameters['owner']))).replace(`{${"repo"}}`, encodeURIComponent(String(requestParameters['repo']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RepoAquariumResponseFromJSON(jsonValue));
    }

    /**
     */
    async getRepoAquarium(requestParameters: GetRepoAquariumRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RepoAquariumResponse> {
        const response = await this.getRepoAquariumRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
